baseURL = 'https://arni.blog/'
languageCode = 'en-us'
title = 'arni.blog'
theme = 'attic'
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[permalinks]
[permalinks.page]
posts = '/:slug/'

[params]
author = 'Arni Hensa'
description = 'I make software and stream weird games'
avatar = '/avatar.png'
images = [ 'og-preview.png' ]

[taxonomies]
topic = 'topics'
tag = 'tags'

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3
