baseURL = 'https://arni.blog/'
languageCode = 'en-us'
title = 'arni.blog'
theme = 'attic'
enableGitInfo = true

[permalinks]
  [permalinks.page]
    posts = '/:slug/'

[params]
author = 'Arni Hensa'
description = 'I make software and stream weird games'
avatar = '/avatar.png'

[taxonomies]
  topic = 'topics'
  tag = 'tags'

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
